# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
<<<<<<< HEAD
  secret_key_base: 0ce83079558f096f6be5910727292d5d694bd1c447f6856a27e7489aff1bb571660a9e3c8cf5ae931c37ded41352ae7da88f9dccf7461f6faf33d24fd1ce81aa
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: 3cb22bd41db7cf30bcab0c3a6ea270f69a1aa6332e82689dee2ca01294e39cf92ae9c1c0ef33d2fef2bfdd15df860bd07d54d2b2250da8f473b1684157f0da98
=======
  secret_key_base: 71ad421ceab46810f4810412eaf187bb43e1dc8ea56d49686c0935c9ea70cf07a36e4ce202b6cced0bb46719da1528129bd41c526363422361364736716c98d7
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
  
test:
  secret_key_base: 3cbe89dffd649b983bba44e1ef13ebda91508bb17cbf46d97dbb9a828a9b71638c70c27837355ae830be1402f1f962ee148d99d800d1ba664cca2427283359f0
>>>>>>> b7fbbf4dfee6277dab38934bcedbf9cf3f3fbe9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
<<<<<<< HEAD
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
=======
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
>>>>>>> b7fbbf4dfee6277dab38934bcedbf9cf3f3fbe9a
